### ISSUE TITLE
BlockLauncher (Pro) crashing when using this mod

### ISSUE THREAD

**Issue by chdxtn** [Vertex-Client/Vertex-Client-PE#62]
i. When I try to use this mod on BlockLauncher(Pro), BLP tends to crash. I don't have any good clues on why that happens ,but it definitely happens.

ii. Erm...How to reproduce?I'm not sure.But I have some details in the next part.

iii. MC(PE): v1.2.2
BLP: v1.17.3
Vertex Client PE: v2.3 & v2.4 (I haven't tested the earlier versions yet)
Device: MyPhone MY33
Android OS: Android 5.1

**Comment by Vertex-Client** [comment]
Hey there, we're sorry for this. Would you mind trying the latest dev version by downloading it from [here](https://raw.githubusercontent.com/Vertex-Client/Vertex-Client-PE/master/Vertex%20Client%20PE.js)? Copy the link and use the 'Import from web address' feature in BlockLauncher.

**Comment by chdxtn** [comment]
org.mozilla.javascript.EcmaError: SyntaxError: Unterminated object literal (Vertex%20Client%20PE.js#150)
	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source)
	at org.mozilla.javascript.NativeJSON.parse(Unknown Source)
	at org.mozilla.javascript.NativeJSON.execIdCall(Unknown Source)
	at org.mozilla.javascript.IdFunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(Vertex%20Client%20PE.js:150)
	at script(Vertex%20Client%20PE.js:146)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:271)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:196)
	at java.lang.Thread.run(Thread.java:818)

**Comment by chdxtn** [comment]
Sorry for the late reply.I have just tested it and (previous comment)

**Comment by Vertex-Client** [comment]
That is a known issue related to the new work in progress language support. The next dev version/commit will fix it.

**Comment by chdxtn** [comment]
Understood.

**Comment by chdxtn** [comment]
Pardon,but how do I get the link to the latest commit?

**Comment by chdxtn** [comment]
The raw code

**Comment by CtrlAltCuteness** [comment]
@BugaMC I thought I should let you know that the current version of Minecraft, even without BL / BL Pro / etc., is actually not stable when you have a cell reception (I don't have access to this home's Wi-Fi, and I do not trust hotspots, so I must deal with the crashing).
The workaround is to either enable Airplane Mode and turn on Wi-Fi, or to just stay logged out of XBL, both which are not ideal solutions.

**Comment by aXxG3TR3KTxX591** [comment]
isStateMod: funct…
org.mozilla.javascript.EvaluatorException: illegal character (vertexdev.js#2827)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(Unknown Source)
	at org.mozilla.javascript.DefaultErrorReporter.error(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.TokenStream.getToken(Unknown Source)
	at org.mozilla.javascript.Parser.peekToken(Unknown Source)
	at org.mozilla.javascript.Parser.matchToken(Unknown Source)
	at org.mozilla.javascript.Parser.propertyName(Unknown Source)
	at org.mozilla.javascript.Parser.name(Unknown Source)
	at org.mozilla.javascript.Parser.primaryExpr(Unknown Source)
	at org.mozilla.javascript.Parser.memberExpr(Unknown Source)
	at org.mozilla.javascript.Parser.unaryExpr(Unknown Source)
	at org.mozilla.javascript.Parser.mulExpr(Unknown Source)
	at org.mozilla.javascript.Parser.addExpr(Unknown Source)
	at org.mozilla.javascript.Parser.shiftExpr(Unknown Source)
	at org.mozilla.javascript.Parser.relExpr(Unknown Source)
	at org.mozilla.javascript.Parser.eqExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitAndExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitXorExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitOrExpr(Unknown Source)
	at org.mozilla.javascript.Parser.andExpr(Unknown Source)
	at org.mozilla.javascript.Parser.orExpr(Unknown Source)
	at org.mozilla.javascript.Parser.condExpr(Unknown Source)
	at org.mozilla.javascript.Parser.assignExpr(Unknown Source)
	at org.mozilla.javascript.Parser.plainProperty(Unknown Source)
	at org.mozilla.javascript.Parser.objectLiteral(Unknown Source)
	at org.mozilla.javascript.Parser.primaryExpr(Unknown Source)
	at org.mozilla.javascript.Parser.memberExpr(Unknown Source)
	at org.mozilla.javascript.Parser.unaryExpr(Unknown Source)
	at org.mozilla.javascript.Parser.mulExpr(Unknown Source)
	at org.mozilla.javascript.Parser.addExpr(Unknown Source)
	at org.mozilla.javascript.Parser.shiftExpr(Unknown Source)
	at org.mozilla.javascript.Parser.relExpr(Unknown Source)
	at org.mozilla.javascript.Parser.eqExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitAndExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitXorExpr(Unknown Source)
	at org.mozilla.javascript.Parser.bitOrExpr(Unknown Source)
	at org.mozilla.javascript.Parser.andExpr(Unknown Source)
	at org.mozilla.javascript.Parser.orExpr(Unknown Source)
	at org.mozilla.javascript.Parser.condExpr(Unknown Source)
	at org.mozilla.javascript.Parser.assignExpr(Unknown Source)
	at org.mozilla.javascript.Parser.variables(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Context.compileImpl(Unknown Source)
	at org.mozilla.javascript.Context.compileReader(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:195)
	at java.lang.Thread.run(Thread.java:762)

**Comment by aXxG3TR3KTxX591** [comment]
Device Samsung galaxy Tab a rooted

**Comment by SWPlaysMC** [comment]
I have a very similar error too. See my commit on this tab.

**Comment by Vertex-Client** [comment]
Closing the issue as there is no longer any activity
